# STT evaluation: WER & TER

Scores each STT provider's transcript against the hand-corrected **golden** reference.

- **WER** (Word Error Rate) = `(substitutions + deletions + insertions) / reference_words`. Lower is better; `0` is perfect.
- **TER** (Translation Edit Rate) = like WER but also credits *shifts* (a phrase moved as a block counts as one edit, not delete+insert). Reported as a percentage.

Inputs live under `data/golden-label/<lecture>/`:

| file | role |
|---|---|
| `golden.md`  | reference (ground truth) |
| `whisper.md` | hypothesis — `whisper_cpp` output |
| `google.md`  | hypothesis — `google_stt` output |

All files share the line format `**[H:MM:SS – H:MM:SS]** text`. We strip the timestamp markers, concatenate the text, then normalize (lowercase, drop punctuation) before scoring — the usual convention so casing/punctuation don't dominate the error rate.

## Setup

`jiwer`, `sacrebleu`, and `pandas` aren't in the project's default deps. Install them into the active env if missing (the project's private index needs auth, so pull these from public PyPI):

```bash
python -m pip install -i https://pypi.org/simple jiwer sacrebleu pandas
```

In [1]:
import re
from pathlib import Path

import jiwer
import pandas as pd
from sacrebleu.metrics import TER

In [2]:
# --- config ---------------------------------------------------------------
# Resolve the repo root whether the notebook runs from repo root or notebooks/.
REPO_ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "data" / "golden-label").exists())
GOLDEN_ROOT = REPO_ROOT / "data" / "golden-label"

REFERENCE_FILE = "golden.md"
# hypothesis filename -> provider label shown in the results table
PROVIDERS = {"whisper.md": "whisper_cpp", "google.md": "google_stt"}

print("repo root:", REPO_ROOT)
print("golden labels:", GOLDEN_ROOT)

repo root: /Users/shamilarslanov/CurrentProjects/autosummary
golden labels: /Users/shamilarslanov/CurrentProjects/autosummary/data/golden-label

## Parsing & normalization

In [3]:
# Matches lines like: **[2:01:41 – 2:01:47]** Item number three for today.
_LINE = re.compile(r"^\s*\*\*\[[^\]]*\]\*\*\s*(.*)$")


def load_transcript(path: Path) -> str:
    """Concatenate the spoken text from a timestamped `.md` transcript into one string."""
    parts = []
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        m = _LINE.match(line)
        if m and m.group(1).strip():
            parts.append(m.group(1).strip())
    return " ".join(parts)


# Standard WER pre-processing: case- and punctuation-insensitive.
_NORMALIZE = jiwer.Compose(
    [
        jiwer.ToLowerCase(),
        jiwer.RemovePunctuation(),
        jiwer.RemoveMultipleSpaces(),
        jiwer.Strip(),
        jiwer.ReduceToListOfListOfWords(),
    ]
)


def normalized_str(text: str) -> str:
    """Apply the same normalization as WER, flattened back to a string (for TER)."""
    return " ".join(w for sentence in _NORMALIZE(text) for w in sentence)

## Score every golden-labelled lecture × provider

In [4]:
ter_metric = TER()
rows = []

for lecture_dir in sorted(p for p in GOLDEN_ROOT.iterdir() if p.is_dir()):
    ref_path = lecture_dir / REFERENCE_FILE
    if not ref_path.exists():
        continue
    reference = load_transcript(ref_path)
    ref_norm = normalized_str(reference)

    for hyp_file, provider in PROVIDERS.items():
        hyp_path = lecture_dir / hyp_file
        if not hyp_path.exists():
            continue
        hypothesis = load_transcript(hyp_path)

        out = jiwer.process_words(
            reference,
            hypothesis,
            reference_transform=_NORMALIZE,
            hypothesis_transform=_NORMALIZE,
        )
        ter = ter_metric.corpus_score([normalized_str(hypothesis)], [[ref_norm]]).score

        rows.append(
            {
                "lecture": lecture_dir.name,
                "provider": provider,
                "ref_words": sum(len(s) for s in _NORMALIZE(reference)),
                "WER": out.wer,
                "TER": ter / 100.0,
                "sub": out.substitutions,
                "del": out.deletions,
                "ins": out.insertions,
                "hits": out.hits,
            }
        )

results = pd.DataFrame(rows)
results

      lecture     provider  ref_words       WER       TER  sub  del  ins  hits
0  lecture-06  whisper_cpp       2090  0.022967  0.022967    7   41    0  2042
1  lecture-06   google_stt       2090  0.162679  0.161722  193   38  109  1859

In [5]:
# Pretty view: rates as percentages, sorted best-first per lecture.
view = results.copy()
view["WER"] = (view["WER"] * 100).round(2).astype(str) + " %"
view["TER"] = (view["TER"] * 100).round(2).astype(str) + " %"
view.sort_values(["lecture", "provider"])

      lecture     provider  ref_words      WER      TER  sub  del  ins  hits
1  lecture-06   google_stt       2090  16.27 %  16.17 %  193   38  109  1859
0  lecture-06  whisper_cpp       2090    2.3 %    2.3 %    7   41    0  2042

## Inspect the errors

A word-level alignment for one lecture/provider — handy for sanity-checking *what* the STT got wrong (`S`=substitution, `D`=deletion, `I`=insertion).

In [6]:
LECTURE = "lecture-06"
HYP_FILE = "google.md"  # switch to "whisper.md" to inspect the other provider

lecture_dir = GOLDEN_ROOT / LECTURE
alignment = jiwer.process_words(
    load_transcript(lecture_dir / REFERENCE_FILE),
    load_transcript(lecture_dir / HYP_FILE),
    reference_transform=_NORMALIZE,
    hypothesis_transform=_NORMALIZE,
)
print(jiwer.visualize_alignment(alignment, skip_correct=True))

=== SENTENCE 1 ===

REF: item number three for today ** selfattention well to actually discuss **** selfattention i need to take a step back and i need to talk to you surprisingly about information retrieval which is not the subject of our class but turns out to be very relevant so how does search work in deep learning how does information retrieval work when you have neural networks well basically it works like this you have the queries query one query two and you have documents document one document two document three document four and in usual information retrieval what you would do you would establish a similarity you need to establish some kind of similarity between queries and documents this kind of similarity will be called relevance and you will train it to be the relevance ***** so it should be higher when this document is relevant to this query this is how search generally works **** whatever it is but when you have deep learning when you have these neural networks that can process any kinds of input and that can train to process long texts large images etc what you usually do is this you get documents through an encoder and the documents will become vectors you get queries through their own encoder so they become vectors too and the idea is that all of these vectors should  live in the same space so even though ** encoders are different they cannot be the same because documents can be images for example so  they are different ** objects but they should produce vectors in the same latent space so like documents get ** mapped over here and then you ***  map your query over here and you are supposed to train the whole system so that the relevant documents will be  close  the the representations of relevant documents will be  close to the representations of the queries so **** then inside this latent space you will be able to just *** **** take nearest neighbors and these nearest neighbors will be a good answer to the search query   ok so i was drawing this but i think i have a picture about   it yea here it is so you have a query you have a document documents go through their own encoders queries go      to   the own encoder and then **** the whole point of it is so that in the latent space in the **** latent space you actually have this structure that relevant documents will be near the images of the queries **** there is a whole field of study about how to do that its obviously    a very big   subfield of learning and we could have a whole class on information   retrieval maybe you will so i wont * **** go into more details but what we need now is this basic intuition that different stuff gets mapped to the same latent space and in that latent space we are just looking for nearest neighbors and since *** ***** you can do it linearly as a linear space basically **** the similarity here between the query and the document ** can be thought of as just the dot product of the corresponding vectors so like i encode the document and i multiply it by the encoding of the query thats it okay and this approach has lots of advantages for information retrieval you can just store the vectors you dont have to think about anything else its fast to do it in the low dimensional space blah blah blah very good and ** selfattention interestingly enough   draws on this intuition but since    its selfattention it applies these ideas to **** the same set of vectors that are both *** *** **** queries and documents **** ** *** **    so here is how it works **** here is how it works here is how it works so we begin with a set of vectors as i said every layer of the transformer gets just a sequence of vectors as input so we have this putting down here x1 x2 and so on * ***   xn we have ****   these vector inputs now i want to make this kind of query document thing so in information retrieval the terminology is inherited from **** classical information retrieval you would sometimes call these images   of documents the representation of documents you would call it the keys **** in classical retrieval the query would not need to be encoded it would be just      the query there is no word for the image of the query but **** we will just call it the query ** lets **** **** say that the query already lives in this space and the document should be mapped there and should produce some kind of a key and here we take our     xs lets say we take x1 and we produce from it queries keys and values so with x1 we multiply it by a matrix called  w q and as a result we get the first query vector this will be q1 **** then we take all of the inputs all of the     xs and we multiply them by the matrix  w k let me just put it here once not to copy it many times and we get the key vectors we get k1 * k2 and so on   kn and *** the whole point of selfattention is that q and k should live in the same latent space so now this guy goes here these guys also go here and the similarity between q and k  is just a dot product between them *** we assume that they already live in ***  this latent space they *** **** **** have the same dimension *** and this similarity is exactly the score that we will use **** as the attention of it so you see     q was made from x ***     k was also made from x and now we look ** like how similar q and    k are between each other so out of this space we get like this sequence of ** attention scores so to say affinities ***** we get **** * *** a11 which is q1 times k1 ** **** and then a12 and so on * *** a1n which is q1 times **    kn so we get this vector of attention ******** affinities we put it through the softmax as usual and we get yes sorry also i forgot *** one detail ill get to it later but we put through the softmax we rescale first by square root of d and then we put it through the  softmax so this kind of transformation ill explain later why *** we need **** rescaling and then we get this vector of attention weights so now we have this **** will be like *  a1 and this will be ***** alpha1 so this is the actual attention weights between 0 and 1 rescaled to sum up to   1 and they are the similarities between the first query *** ***** ***** and all the keys right similarities rescaled back to a set of weights so now we need to use the set of weights to make some kind of linear combination to make a  convex combination of something well of what of another set of vectors here is the thing so now we again take all of the     xs and we multiply them by yet another matrix weight matrix wv and we get vectors that we call values ** **** v1 v2 vn values so the green ones are ****** values the blue ones are keys and the red ones are queries and now we take all of these values and we multiply them with the dot product we multiply them we add them up with the coefficients alpha so this is what this is whats the dot product how do i write this right ***** anyway dot product so the output is lets call     it z1 its the sum of ***** *** alpha1i times vi okay and thats it thats the basic idea of selfattention and of course i only drew one query but it then gets repeated so we take x2 we multiply it by wq we get q2 it also gets mapped here blah blah blah and   as the output     we get z2 which is the sum of alpha 2i again times * vi and vi       is our vectors right so this takes a little bit of understanding yeah cosine similarity **** right so this takes a little bit of understanding to get it in your head because its all very abstract right its just some dot products  in some new space and this new space is just multiplication by the weight matrices there is nothing **** ** ******* too intuitive here well i tried to give you the basic intuition for information retrieval but i mean it only goes so far still formally its really really simple *** right so what we do *** formally is we take the   axis   we multiply them by      a matrix we    get    the  queries so in practice of course you would not do it step by step you would do it all at once so **** your  queries are some weight matrix times x or maybe the other way around ** i forget which one is more   common   maybe x times this  matrix it doesnt matter and your keys are some weight matrix times x and your  values   this   is k are some weight matrix times x right and then what do you do with ****  these matrices so if we continue the formal stuff you need to get this matrix of all possible cosine similarities you write all possible dot products between queries and keys so if you write it in matrix forms then it will be like q times k transpose this will be the matrix where the ijs element will be like qi dot product by kj  right and then you take this     q times k transpose and ****  you rescale you do ** softmax and then you multiply by the result the vectors     v so the attention weights are the softmax of one of the square root of d q k transpose and the actual output      dz is ****  softmax of one over the square root of d q k transpose times v and thats the main formula that you see everywhere right this **** is from the original attention is all you need paper and this is exactly what i was trying to explain to you here so the intuition about *** ****  these matrices their dimensions and everything is that    x is probably pretty big pretty long its from some   r to i dont know some capital d and queries and keys have to live in the same space we have to make dot products with them so they both have to be  living in the same smaller space small d so this matrix and this matrix are both like   d times small d matrices and ****** values formally can have a different size right we never take a dot product between v and q or v and k so formally it could be like    d prime in practice usually its the same    d of course but formally let me write that this is like a d times d prime matrix ** or sorry the way *** *** i write it it should be that way around    it should be d times capital d and this should be        d  prime times capital d okay so what else can i say here  what else can i say here i think thats it for the basic idea of selfattention we got from the beginning to the end i will show you a nicer picture in a sec let me just highlight one thing ** **** **** sorry i promised to explain where the square root of      d comes from why *** the rescaling well the **** rescaling goes like this what we have here what we have in this raw affinities between queries and keys are like dot products between vectors of length     d and if you think of say queries and keys  as just random vectors vectors with random numbers inside you see that what do you see you see something dont you you see that these vectors with queries and keys inside *** if you think of them  as just random vectors so **** ** lets say its like qi is something like    0 plus or minus 1 right so its something from minus   1 to   1 on ***** average maybe more maybe less but more or less it has **** a standard deviation of   1 around    0 and kj also has a standard deviation of   1 around 0 then what is happening here this is the sum of d batch numbers with deviation   1 and if you take the sum of   d random variables each of which can go to plus or minus *** *             1 on average then the result will have a variance on the order of give or take square root of d